### ISSUE TITLE
\autoterms overrides everything after first filles cell

### ISSUE THREAD

**Issue by ghost** [2pi/karnaugh-map#1]
\autoterms overrides everything after the first filled cell. It fills everything with specified (or default) character except the first cell that was not empty. For example:

``` latex
\begin{karnaugh-map}
  \minterms{2, 6, 9, 11, 13, 15}
  \autoterms[0]
\end{karnaugh-map}
```

In this example my pdf output shows 0s in every cell except cell 2. And in cells 6, 9, 11, 13 and 15 there are both 0 and 1 on top of each other.

**EDIT:** It appears this only happens it you put spaces after the commas in the minterms. It works fine with `\minterms{2,6,9,11,13,15}`.

**Comment by 2pi** [comment]
As shown in your edit, it does not handle spaces. Lists should be comma separated without spaces or anything else. Sorry for the confusion!

**Comment by 2pi** [comment]
Room for improvement in documentation.
