### ISSUE TITLE
FeatureRequest: specify colors of implicants

### ISSUE THREAD

**Issue by ghost** [2pi/karnaugh-map#13]
Hello, I want to reuse the color as you can see here for every \implicant another color will be used:
![2020-02-29_21-45](https://user-images.githubusercontent.com/27790087/75614819-eec0ce80-5b3c-11ea-995b-da7be2abde2c.png)
green should be red also yellow and blue should be green since I want to create a DNF which is green and a KNF which is red so I can memorize it easier for me.
Would it be possible something like \implicant{}{}{}{} where another two {} will be another implicant but with the same color?

**Comment by gunqqer** [comment]
#14 is working on something like this, but you can always use `%\advance\@karnaughmap@var@colorindex@ by -1\relax` to go back 1 color, bit hacky but it works.

**Comment by 2pi** [comment]
Thanks for opening this issue, there have been multiple request for this feature so I'm reopening this. I've slowly been thinking and working on this and would like some API feedback. The two possible ways I see is;

**1. Option:** Use package and environment options to specify the color scheme. Something like
```
\begin{karnaugh-map}(implicantcolors=red,green,yellow)
\end{karnaugh-map}
```
**2. New command:** adding options like above might be most intuitive from a structural perspective, but the list of options gets pretty long quite quickly. So the second suggestion is adding a new command like
```
\KarnaughMapImplicantColors{red,green,yellow}
```
My thinking is that one would probably want the same color scheme throughout the document and would therefore probably define the color scheme at the beginning of the document and not customize each karnaugh map. Thereby the second alternative might be easiest to work with and read...

Please let me know if you have any input! Thanks in advance.
