### ISSUE TITLE
\newcount misplaced

### ISSUE THREAD

**Issue by eg9** [2pi/karnaugh-map#15]
The code of the package has several `\newcount` commands buried in definitions, which means that a whole new lot is allocated. For instance in a log file I read
```
\@karnaughmap@local@northwest@=\count295
\@karnaughmap@local@southeast@=\count296
\@karnaughmap@local@northwest@=\count297
\@karnaughmap@local@southeast@=\count298
```
and this will be replicated with new numbers at each call of the environment.

The correct programming style is to declare the counters at the outer level and then to set them to zero when needed. So all the `\newcount` declaration should go, say, at the beginning of the `.sty` file and the present `\newcount<cs>` instructions should become
```
\@karnaughmap@local@northwest@=\z@
```
and so on.

**Comment by 2pi** [comment]
Thank you @eg9 for the detailed explanation and I'm sorry for the late response!

I've tried it out, while I didn't notice much of a difference I do see where it comes from. If you know of any good documentation related to this or allocations in general I would love to read it. I did a quick search just now and came up with much.

I'll have a look at making the changes after I've applied a few other patches I've laying around. I suppose a similar tactic also applies to `\newcommand` inside definitions?
