### ISSUE TITLE
Support for more templates

### ISSUE THREAD

**Issue by yklcs** [2pi/karnaugh-map#19]
Support for more templates will be nice to have.
For example, 8x4x1 maps are frequently used for 5 variable K-maps. I don't see anything blocking support for them.
Custom template specifications would be helpful in the long run.

I'll take a look and open a PR if I can.

**Comment by 2pi** [comment]
Thanks for the suggestion. However 5 variable karnaugh maps are already supported using the below example code;

    \begin{karnaugh-map}[4][4][2]
    \end{karnaugh-map}

The generated map should look like [this](https://github.com/2pi/karnaugh-map/blob/15b844f8c19ed1f9e48781fd2e009530a6ffe2c7/test/expected/karnaugh-442-grid.pdf). Does this solve your problem?
