### ISSUE TITLE
No way to scale

### ISSUE THREAD

**Issue by jmerdich** [2pi/karnaugh-map#2]
Some way to scale the outputted tikzpictures (or style hooks in general) would be very useful.

**Comment by 2pi** [comment]
Could you elaborate a bit more on what scaling would mean and how it would be exposed api-wise. Regarding "style hooks in general" do you mean setting font type, font size, colors and similar?

**Possible solution:** This will literally just scale the picture but it may be what you want...? Anyway using the `resizebox` command from `graphicx` you can specify the width, height, and the object. Exclamation mark in either width or height while specifying the other one will preserve the aspect ratio. The example below scales the karnaugh map to be as wide as the column width while preserving the aspect ratio.
```latex
\resizebox{\columnwidth}{!}{
  \begin{karnaugh-map}
  \end{karnaugh-map}
}
```

**Comment by 2pi** [comment]
Add "Possible solution" from above to documentation

**Comment by 2pi** [comment]
I've updated the documentation giving an example of resizing.
