### ISSUE TITLE
Add Documentation to Github

### ISSUE THREAD

**Issue by ukanuk** [2pi/karnaugh-map#23]
If the documentation http://mirrors.ctan.org/graphics/pgf/contrib/karnaugh-map/karnaugh-map.pdf and source `karnaugh-map.tex` were in this repository, I could submit pull requests to suggest fixes for #20 and #22. As it stands, the community cannot help resolve these.

Or perhaps the documentation is stored elsewhere that is standard for TeX packages and I simply didn't know! In which case, please point me in the correct direction.

**Comment by 2pi** [comment]
The source for the pdf documentation is located in the [karnaugh-map.dtx](https://github.com/2pi/karnaugh-map/blob/master/karnaugh-map.dtx) file. Build instructions are in the [README](https://github.com/2pi/karnaugh-map?tab=readme-ov-file#installation).

**Comment by ukanuk** [comment]
Thank you! I hope to / intend to address #20 and #22. And maybe also submit a change to layering so that implicants are drawn on top of the grid but underneath the implicants. 

But first I need my personal laptop back so that I can use regular TeX to compile. I'm currently using Overleaf in the browser with borrowed computers, and afaik Overleaf does not support DTX. I had to send in my personal laptop for warranty repair, and they've had it for a month now with no ETA.
