### ISSUE TITLE
Position of input variables

### ISSUE THREAD

**Issue by oscargus** [2pi/karnaugh-map#3]
Just found this excellent package and will post some improvement suggestions. One issue for each for simpler tracking.

I'm used to write the variables in the top left corner as

```
 \cd
  \
ab \
```
(Ugly image, but I think you get the idea, it is how it was done in the StackExchange code which I used earlier.)

It would be nice if this was optional in some way.

**Comment by 2pi** [comment]
Related http://tex.stackexchange.com/questions/343055/drawing-karnaugh-map-modification-in-karnaugh-map-package

**Comment by 2pi** [comment]
My suggestion is to specify this as an option when importing the package, as you probably want the same style throughout the document.

Using this for the default:
`\usepackage[label=middle]{karnaugh-map}`

And this for your suggested design:
`\usepackage[label=corner]{karnaugh-map}`

Any thoughts on this API?

Further, I have a question; when you use 5 or 6 variables do you add the label to each submap or just to the top-left submap? How about the submap labels?

Ping: @oscargus

**Comment by functionpointer** [comment]
That API sounds awesome.
