### ISSUE TITLE
Overlapping symbols with \autoterms

### ISSUE THREAD

**Issue by ylfchild** [2pi/karnaugh-map#8]
When using `\autoterms` in two successive k-maps,  some cells have both a value and a `-` marking overlaid in them.

A small working example is below:

```
\documentclass{article}
\usepackage{karnaugh-map}

\begin{document}


    \begin{karnaugh-map}[2][2][1]
      \minterms{2}
      \maxterms{0, 1}
      \autoterms
    \end{karnaugh-map}

  \begin{karnaugh-map}[2][2][1]
    \minterms{0,1}
    \maxterms{3}
    \autoterms
  \end{karnaugh-map}

\end{document}

```

**Comment by ylfchild** [comment]
Nevermind! I found the same closed issue, and the problem is actually with my `\maxterms{0, 1}` list having a space in it.

**Comment by 2pi** [comment]
Duplicate of #1
